name: NuGet Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test with XUnit
      run: dotnet test ./PathCat.Tests/PathCat.Tests.csproj --no-build --verbosity normal --logger "console;verbosity=detailed"
    
    - name: Pack
      run: dotnet pack ./PathCat/PathCat.csproj --no-build --configuration Release -o ./nupkg
    
    - name: Push to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate